/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import BO.AulaBO;
import Entidad.Aula;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabiola Mora
 */
public class AulaVista extends javax.swing.JFrame {

    /**
     * Creates new form AulaVista
     */
    private AulaBO aBO = new AulaBO();

    public AulaVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Fondo_geeneral = new javax.swing.JPanel();
        Fondo_nav = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        CAPACIDAD = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        PABELLON = new javax.swing.JLabel();
        txtCapacidad = new javax.swing.JTextField();
        txxtIDPabellon = new javax.swing.JTextField();
        LOGO2 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JButton();
        Limipiar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("ID");

        jPanel15.setBackground(new java.awt.Color(153, 153, 255));
        jPanel15.setName("MENU"); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        jLabel15.setName("MENUbtn"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel16.setText("MENÚ");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel15)
                .addGap(70, 70, 70)
                .addComponent(jLabel16)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(14, 14, 14))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo_geeneral.setBackground(new java.awt.Color(255, 255, 255));
        Fondo_geeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fondo_nav.setBackground(new java.awt.Color(51, 51, 255));

        Titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        Titulo.setText("ESCUELA LENGUAJE BD");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ESCUELA (2).png"))); // NOI18N

        Menu.setBackground(new java.awt.Color(153, 153, 255));
        Menu.setName("MENU"); // NOI18N
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuMousePressed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        jLabel17.setName("MENUbtn"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel18.setText("MENÚ");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout Fondo_navLayout = new javax.swing.GroupLayout(Fondo_nav);
        Fondo_nav.setLayout(Fondo_navLayout);
        Fondo_navLayout.setHorizontalGroup(
            Fondo_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_navLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(Logo)
                .addGap(41, 41, 41)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        Fondo_navLayout.setVerticalGroup(
            Fondo_navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_navLayout.createSequentialGroup()
                .addComponent(Logo)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_navLayout.createSequentialGroup()
                .addComponent(Titulo)
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Fondo_navLayout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Fondo_geeneral.add(Fondo_nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 830, 120));

        CAPACIDAD.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CAPACIDAD.setText("Capacidad");
        Fondo_geeneral.add(CAPACIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 241, -1, -1));
        Fondo_geeneral.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 401, -1, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        Fondo_geeneral.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 172, 179, 36));

        ID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ID.setText("ID");
        Fondo_geeneral.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 178, -1, -1));

        PABELLON.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PABELLON.setText("ID Pabellon");
        Fondo_geeneral.add(PABELLON, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 328, -1, -1));
        Fondo_geeneral.add(txtCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 235, 179, 36));
        Fondo_geeneral.add(txxtIDPabellon, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 314, 179, 36));

        LOGO2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aula.png"))); // NOI18N
        Fondo_geeneral.add(LOGO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        Eliminar.setBackground(new java.awt.Color(204, 204, 204));
        Eliminar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        Fondo_geeneral.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 160, 40));

        Limipiar.setBackground(new java.awt.Color(204, 204, 204));
        Limipiar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Limipiar.setText("Limpiar");
        Limipiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimipiarActionPerformed(evt);
            }
        });
        Fondo_geeneral.add(Limipiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 160, 40));

        Modificar.setBackground(new java.awt.Color(204, 204, 204));
        Modificar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        Fondo_geeneral.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 160, 40));

        Agregar.setBackground(new java.awt.Color(204, 204, 204));
        Agregar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        Fondo_geeneral.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo_geeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Fondo_geeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void MenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMousePressed
        this.setVisible(false);
        Menu v = new Menu();
        v.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_MenuMousePressed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:
        
        if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el ID");
        } else {
            
            String mensaje = aBO.eliminarAula(Integer.parseInt(txtID.getText()));
            System.out.println(mensaje);
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        
         if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el ID");
        }
        if (txtCapacidad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue la capacidad");
        }
        if (txxtIDPabellon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el pabellon");
        } else {
            
            Aula a = new Aula();

            a.setID_AULA(Integer.parseInt(txtID.getText()));
            a.setCAPACIDAD_AULA(Integer.parseInt(txtCapacidad.getText()));
            a.setID_PABELLON(Integer.parseInt(txxtIDPabellon.getText()));

            String mensaje = aBO.ModificarAula(a);
        }
        
    }//GEN-LAST:event_ModificarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:

        if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el ID");
        }
        if (txtCapacidad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue la capacidad");
        }
        if (txxtIDPabellon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el pabellon");
        } else {
            
            Aula a = new Aula();

            a.setID_AULA(Integer.parseInt(txtID.getText()));
            a.setCAPACIDAD_AULA(Integer.parseInt(txtCapacidad.getText()));
            a.setID_PABELLON(Integer.parseInt(txxtIDPabellon.getText()));

            String mensaje = aBO.agregarAula(a);
        }
    }//GEN-LAST:event_AgregarActionPerformed

    private void LimipiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimipiarActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        txxtIDPabellon.setText("");
        txtCapacidad.setText("");
    }//GEN-LAST:event_LimipiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AulaVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JLabel CAPACIDAD;
    private javax.swing.JButton Eliminar;
    private javax.swing.JPanel Fondo_geeneral;
    private javax.swing.JPanel Fondo_nav;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel LOGO2;
    private javax.swing.JButton Limipiar;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel PABELLON;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txxtIDPabellon;
    // End of variables declaration//GEN-END:variables
}
