/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import BO.EstudianteBO;
import Entidad.Aula;
import Entidad.Estudiante;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabiola Mora
 */
public class EstudianteVista extends javax.swing.JFrame {

    private EstudianteBO aBO = new EstudianteBO();
    /**
     * Creates new form Estudiante
     */
    public EstudianteVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        IDProvincia = new javax.swing.JLabel();
        txtApellido1 = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        Apellido1 = new javax.swing.JLabel();
        txtIDProvincia = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido2 = new javax.swing.JTextField();
        txtIDMadre = new javax.swing.JTextField();
        txtIDPadre = new javax.swing.JTextField();
        Apellido2 = new javax.swing.JLabel();
        IDMadre = new javax.swing.JLabel();
        IDPadre = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();
        Limipiar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setText("ESCUELA LENGUAJE BD");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ESCUELA (2).png"))); // NOI18N

        Menu.setBackground(new java.awt.Color(153, 153, 255));
        Menu.setName("MENU"); // NOI18N
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuMousePressed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        jLabel17.setName("MENUbtn"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel18.setText("MENÚ");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 830, 120));

        IDProvincia.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IDProvincia.setText("ID provincia");
        jPanel2.add(IDProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        txtApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 179, 36));

        ID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ID.setText("ID");
        jPanel2.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 179, 36));

        Nombre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Nombre.setText("Nombre");
        jPanel2.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        Apellido1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Apellido1.setText("Apellido 1");
        jPanel2.add(Apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        txtIDProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDProvinciaActionPerformed(evt);
            }
        });
        jPanel2.add(txtIDProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 179, 36));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 179, 36));

        txtApellido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido2ActionPerformed(evt);
            }
        });
        jPanel2.add(txtApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 179, 36));

        txtIDMadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDMadreActionPerformed(evt);
            }
        });
        jPanel2.add(txtIDMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 179, 36));

        txtIDPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDPadreActionPerformed(evt);
            }
        });
        jPanel2.add(txtIDPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 179, 36));

        Apellido2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Apellido2.setText("Apellido 2");
        jPanel2.add(Apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        IDMadre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IDMadre.setText("ID madre");
        jPanel2.add(IDMadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        IDPadre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IDPadre.setText("ID padre");
        jPanel2.add(IDPadre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/estudiante.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        Agregar.setBackground(new java.awt.Color(204, 204, 204));
        Agregar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jPanel2.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 160, 40));

        Limipiar.setBackground(new java.awt.Color(204, 204, 204));
        Limipiar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Limipiar.setText("Limpiar");
        Limipiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimipiarActionPerformed(evt);
            }
        });
        jPanel2.add(Limipiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 160, 40));

        Modificar.setBackground(new java.awt.Color(204, 204, 204));
        Modificar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPanel2.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 160, 40));

        Eliminar.setBackground(new java.awt.Color(204, 204, 204));
        Eliminar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel2.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDPadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDPadreActionPerformed

    private void txtIDMadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDMadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDMadreActionPerformed

    private void txtApellido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido2ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtIDProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDProvinciaActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido1ActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:

        if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el ID");
        }
        if (txtApellido1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue primer apellido");
        }
        if (txtApellido2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue elsegundo apellido");
        }
        if (txtIDMadre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el ID de la madre");
        }
        if (txtIDPadre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el ID del padre");
        }
        if (txtIDProvincia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el ID de la provincia");
        } 
         if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el nombre del estudiante");
        }else {

            Estudiante a = new Estudiante();

            a.setID_ESTUDIANTE(Integer.parseInt(txtID.getText()));
            a.setID_MADRE(Integer.parseInt(txtIDMadre.getText()));
            a.setID_PADRE(Integer.parseInt(txtIDPadre.getText()));
            a.setID_PROVINCIA(Integer.parseInt(txtIDProvincia.getText()));
            a.setNOMBRE(txtNombre.getText());
            a.setAPELLIDO1(txtApellido1.getText());
            a.setAPELLIDO2(txtApellido2.getText());
            
            

            String mensaje = aBO.agregarEstudiante(a);
        }
    }//GEN-LAST:event_AgregarActionPerformed

    private void LimipiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimipiarActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        txtApellido1.setText("");
        txtApellido2.setText("");
        txtIDMadre.setText("");
        txtIDPadre.setText("");
        txtIDProvincia.setText("");
        txtNombre.setText("");
    }//GEN-LAST:event_LimipiarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:

         if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el ID");
        }
        if (txtApellido1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue primer apellido");
        }
        if (txtApellido2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue elsegundo apellido");
        }
        if (txtIDMadre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el ID de la madre");
        }
        if (txtIDPadre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el ID del padre");
        }
        if (txtIDProvincia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el ID de la provincia");
        } 
         if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el nombre del estudiante");
        }else {

            Estudiante a = new Estudiante();

            a.setID_ESTUDIANTE(Integer.parseInt(txtID.getText()));
            a.setID_MADRE(Integer.parseInt(txtIDMadre.getText()));
            a.setID_PADRE(Integer.parseInt(txtIDPadre.getText()));
            a.setID_PROVINCIA(Integer.parseInt(txtIDProvincia.getText()));
            a.setNOMBRE(txtNombre.getText());
            a.setAPELLIDO1(txtApellido1.getText());
            a.setAPELLIDO2(txtApellido2.getText());
            
            

            String mensaje = aBO.ModificarEstudiante(a);
        }

    }//GEN-LAST:event_ModificarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:

        if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el ID");
        } else {

            String mensaje = aBO.eliminarEstudiante(Integer.parseInt(txtID.getText()));
            System.out.println(mensaje);
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void MenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMousePressed
        this.setVisible(false);
        Menu v=new Menu();
        v.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_MenuMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudianteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudianteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudianteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudianteVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudianteVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JLabel Apellido1;
    private javax.swing.JLabel Apellido2;
    private javax.swing.JButton Eliminar;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel IDMadre;
    private javax.swing.JLabel IDPadre;
    private javax.swing.JLabel IDProvincia;
    private javax.swing.JButton Limipiar;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDMadre;
    private javax.swing.JTextField txtIDPadre;
    private javax.swing.JTextField txtIDProvincia;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
