/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Fabiola Mora
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Madre = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Padre = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Nota = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Matricula = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Curso = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Profesor = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Pabellon = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Aula = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Horario = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        Estudiante = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(153, 153, 255));
        jPanel15.setName("MENU"); // NOI18N
        jPanel15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel15MouseMoved(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        jLabel15.setName("MENUbtn"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel16.setText("MENÚ");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel15)
                .addGap(70, 70, 70)
                .addComponent(jLabel16)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(14, 14, 14))
        );

        jPanel2.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 24, -1, -1));

        Madre.setBackground(new java.awt.Color(204, 204, 255));
        Madre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Madre.setName("madre"); // NOI18N
        Madre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MadreMousePressed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tutor.png"))); // NOI18N
        jLabel17.setName("MENUbtn"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel18.setText("Madre");

        javax.swing.GroupLayout MadreLayout = new javax.swing.GroupLayout(Madre);
        Madre.setLayout(MadreLayout);
        MadreLayout.setHorizontalGroup(
            MadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MadreLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel17)
                .addGap(71, 71, 71)
                .addComponent(jLabel18)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        MadreLayout.setVerticalGroup(
            MadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MadreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addGap(14, 14, 14))
        );

        jPanel2.add(Madre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 310, 40));

        Padre.setBackground(new java.awt.Color(204, 204, 255));
        Padre.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Padre.setName("padre"); // NOI18N
        Padre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PadreMousePressed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tutor.png"))); // NOI18N
        jLabel19.setName("MENUbtn"); // NOI18N

        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel20.setText("Padre");

        javax.swing.GroupLayout PadreLayout = new javax.swing.GroupLayout(Padre);
        Padre.setLayout(PadreLayout);
        PadreLayout.setHorizontalGroup(
            PadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PadreLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel19)
                .addGap(72, 72, 72)
                .addComponent(jLabel20)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        PadreLayout.setVerticalGroup(
            PadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PadreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(14, 14, 14))
        );

        jPanel2.add(Padre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 310, 40));

        Nota.setBackground(new java.awt.Color(204, 204, 255));
        Nota.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Nota.setName("nota"); // NOI18N
        Nota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NotaMousePressed(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nota.png"))); // NOI18N
        jLabel21.setName("MENUbtn"); // NOI18N

        jLabel22.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel22.setText("Nota");

        javax.swing.GroupLayout NotaLayout = new javax.swing.GroupLayout(Nota);
        Nota.setLayout(NotaLayout);
        NotaLayout.setHorizontalGroup(
            NotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel21)
                .addGap(70, 70, 70)
                .addComponent(jLabel22)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        NotaLayout.setVerticalGroup(
            NotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NotaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(14, 14, 14))
        );

        jPanel2.add(Nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 310, 40));

        Matricula.setBackground(new java.awt.Color(204, 204, 255));
        Matricula.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Matricula.setName("matricula"); // NOI18N
        Matricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MatriculaMousePressed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lapiz.png"))); // NOI18N
        jLabel23.setName("MENUbtn"); // NOI18N

        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel24.setText("Matrícula");

        javax.swing.GroupLayout MatriculaLayout = new javax.swing.GroupLayout(Matricula);
        Matricula.setLayout(MatriculaLayout);
        MatriculaLayout.setHorizontalGroup(
            MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MatriculaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel23)
                .addGap(68, 68, 68)
                .addComponent(jLabel24)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        MatriculaLayout.setVerticalGroup(
            MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MatriculaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MatriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(14, 14, 14))
        );

        jPanel2.add(Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 310, 40));

        Curso.setBackground(new java.awt.Color(204, 204, 255));
        Curso.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Curso.setName("curso"); // NOI18N
        Curso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CursoMousePressed(evt);
            }
        });

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curso.png"))); // NOI18N
        jLabel25.setName("MENUbtn"); // NOI18N

        jLabel26.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel26.setText("Curso");

        javax.swing.GroupLayout CursoLayout = new javax.swing.GroupLayout(Curso);
        Curso.setLayout(CursoLayout);
        CursoLayout.setHorizontalGroup(
            CursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CursoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel25)
                .addGap(70, 70, 70)
                .addComponent(jLabel26)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        CursoLayout.setVerticalGroup(
            CursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CursoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(14, 14, 14))
        );

        jPanel2.add(Curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 310, 40));

        Profesor.setBackground(new java.awt.Color(204, 204, 255));
        Profesor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Profesor.setName("profesor"); // NOI18N
        Profesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProfesorMousePressed(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profesor.png"))); // NOI18N
        jLabel27.setName("MENUbtn"); // NOI18N

        jLabel28.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel28.setText("Profesor");

        javax.swing.GroupLayout ProfesorLayout = new javax.swing.GroupLayout(Profesor);
        Profesor.setLayout(ProfesorLayout);
        ProfesorLayout.setHorizontalGroup(
            ProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfesorLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel27)
                .addGap(70, 70, 70)
                .addComponent(jLabel28)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        ProfesorLayout.setVerticalGroup(
            ProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfesorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addGap(14, 14, 14))
        );

        jPanel2.add(Profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 310, 40));

        Pabellon.setBackground(new java.awt.Color(204, 204, 255));
        Pabellon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Pabellon.setName("pabellon"); // NOI18N
        Pabellon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PabellonMousePressed(evt);
            }
        });

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/escuela (3).png"))); // NOI18N
        jLabel29.setName("MENUbtn"); // NOI18N

        jLabel30.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel30.setText("Pabellon");

        javax.swing.GroupLayout PabellonLayout = new javax.swing.GroupLayout(Pabellon);
        Pabellon.setLayout(PabellonLayout);
        PabellonLayout.setHorizontalGroup(
            PabellonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PabellonLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel29)
                .addGap(70, 70, 70)
                .addComponent(jLabel30)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        PabellonLayout.setVerticalGroup(
            PabellonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PabellonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PabellonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addGap(14, 14, 14))
        );

        jPanel2.add(Pabellon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 310, 40));

        Aula.setBackground(new java.awt.Color(204, 204, 255));
        Aula.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Aula.setName("aula"); // NOI18N
        Aula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AulaMousePressed(evt);
            }
        });

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aula.png"))); // NOI18N
        jLabel31.setName("MENUbtn"); // NOI18N

        jLabel32.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel32.setText("Aula");

        javax.swing.GroupLayout AulaLayout = new javax.swing.GroupLayout(Aula);
        Aula.setLayout(AulaLayout);
        AulaLayout.setHorizontalGroup(
            AulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AulaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel31)
                .addGap(72, 72, 72)
                .addComponent(jLabel32)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        AulaLayout.setVerticalGroup(
            AulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AulaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addGap(14, 14, 14))
        );

        jPanel2.add(Aula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 310, 40));

        Horario.setBackground(new java.awt.Color(204, 204, 255));
        Horario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Horario.setName("horario"); // NOI18N
        Horario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HorarioMousePressed(evt);
            }
        });

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/horario.png"))); // NOI18N
        jLabel33.setName("MENUbtn"); // NOI18N

        jLabel34.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel34.setText("Horario");

        javax.swing.GroupLayout HorarioLayout = new javax.swing.GroupLayout(Horario);
        Horario.setLayout(HorarioLayout);
        HorarioLayout.setHorizontalGroup(
            HorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HorarioLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel33)
                .addGap(68, 68, 68)
                .addComponent(jLabel34)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        HorarioLayout.setVerticalGroup(
            HorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HorarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addGap(14, 14, 14))
        );

        jPanel2.add(Horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 310, 40));

        Estudiante.setBackground(new java.awt.Color(204, 204, 255));
        Estudiante.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Estudiante.setName("Estudiante"); // NOI18N
        Estudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EstudianteMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/estudiante.png"))); // NOI18N
        jLabel3.setName("MENUbtn"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setText("Estudiante");

        javax.swing.GroupLayout EstudianteLayout = new javax.swing.GroupLayout(Estudiante);
        Estudiante.setLayout(EstudianteLayout);
        EstudianteLayout.setHorizontalGroup(
            EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstudianteLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addGap(69, 69, 69)
                .addComponent(jLabel4)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        EstudianteLayout.setVerticalGroup(
            EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EstudianteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14))
        );

        jPanel2.add(Estudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 310, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 495));

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel2.setText("ESCUELA LENGUAJE BD");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ESCUELA (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(92, 92, 92))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16))))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 580, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sube-y-baja-96.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 100, 100));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("En este sistema usted podrá hacer consultas sobre los aspectos más relevantes ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("relacionados a la gestión de datos de la Escuela Lenguaje BD");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-x-32.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
       System.exit(0);
    }//GEN-LAST:event_jLabel8MousePressed

    private void jPanel15MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel15MouseMoved

    private void EstudianteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstudianteMousePressed
            this.setVisible(false);
            EstudianteVista v=new EstudianteVista();
            v.setVisible(true);
    }//GEN-LAST:event_EstudianteMousePressed

    private void MadreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MadreMousePressed
            this.setVisible(false);
            MadreVista v=new MadreVista();
            v.setVisible(true);
    }//GEN-LAST:event_MadreMousePressed

    private void PadreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PadreMousePressed
            this.setVisible(false);
            PadreVista v=new PadreVista();
            v.setVisible(true);
    }//GEN-LAST:event_PadreMousePressed

    private void NotaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NotaMousePressed
            this.setVisible(false);
            NotaVista v=new NotaVista();
            v.setVisible(true);
    }//GEN-LAST:event_NotaMousePressed

    private void MatriculaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatriculaMousePressed
            this.setVisible(false);
            MatriculaVista v=new MatriculaVista();
            v.setVisible(true);
    }//GEN-LAST:event_MatriculaMousePressed

    private void CursoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CursoMousePressed
            this.setVisible(false);
            CursoVista v=new CursoVista();
            v.setVisible(true);
    }//GEN-LAST:event_CursoMousePressed

    private void ProfesorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfesorMousePressed
            this.setVisible(false);
           ProfesorVista v=new ProfesorVista();
            v.setVisible(true);
    }//GEN-LAST:event_ProfesorMousePressed

    private void PabellonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PabellonMousePressed
            this.setVisible(false);
           PabellonVista v=new PabellonVista();
            v.setVisible(true);
    }//GEN-LAST:event_PabellonMousePressed

    private void AulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AulaMousePressed
            this.setVisible(false);
            AulaVista v=new AulaVista();
            v.setVisible(true);
    }//GEN-LAST:event_AulaMousePressed

    private void HorarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HorarioMousePressed
            this.setVisible(false);
           HorarioVista v=new HorarioVista();
            v.setVisible(true);
    }//GEN-LAST:event_HorarioMousePressed

    
    void setColor(JPanel panel){
        panel.setBackground(new Color(85,65,118));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(85,65,118));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Aula;
    private javax.swing.JPanel Curso;
    private javax.swing.JPanel Estudiante;
    private javax.swing.JPanel Horario;
    private javax.swing.JPanel Madre;
    private javax.swing.JPanel Matricula;
    private javax.swing.JPanel Nota;
    private javax.swing.JPanel Pabellon;
    private javax.swing.JPanel Padre;
    private javax.swing.JPanel Profesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
