/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import BO.NotaBO;
import Entidad.Nota;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabiola Mora
 */
public class NotaVista extends javax.swing.JFrame {

    private NotaBO aBO = new NotaBO();

    /**
     * Creates new form Nota
     */
    public NotaVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        IDTrimestre = new javax.swing.JLabel();
        txtIDTrimestre = new javax.swing.JTextField();
        IDCurso = new javax.swing.JLabel();
        txtIDCurso = new javax.swing.JTextField();
        IDEstudiante = new javax.swing.JLabel();
        txtIDEstudiante = new javax.swing.JTextField();
        Nota = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        Agregar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Limipiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 51, 255));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel3.setText("ESCUELA LENGUAJE BD");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ESCUELA (2).png"))); // NOI18N

        Menu.setBackground(new java.awt.Color(153, 153, 255));
        Menu.setName("MENU"); // NOI18N
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MenuMousePressed(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.png"))); // NOI18N
        jLabel19.setName("MENUbtn"); // NOI18N

        jLabel20.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel20.setText("MENÚ");

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3)
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 830, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nota.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        ID.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ID.setText("ID");
        jPanel1.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 179, 36));

        IDTrimestre.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IDTrimestre.setText("ID Trimestre");
        jPanel1.add(IDTrimestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        txtIDTrimestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDTrimestreActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDTrimestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 179, 36));

        IDCurso.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IDCurso.setText("ID Curso");
        jPanel1.add(IDCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        txtIDCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDCursoActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 179, 36));

        IDEstudiante.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IDEstudiante.setText("ID Estudiante");
        jPanel1.add(IDEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        txtIDEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDEstudianteActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 179, 36));

        Nota.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Nota.setText("Nota");
        jPanel1.add(Nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        txtNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 179, 36));

        Agregar.setBackground(new java.awt.Color(204, 204, 204));
        Agregar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jPanel1.add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 160, 40));

        Modificar.setBackground(new java.awt.Color(204, 204, 204));
        Modificar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPanel1.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, 160, 40));

        Eliminar.setBackground(new java.awt.Color(204, 204, 204));
        Eliminar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 160, 40));

        Limipiar.setBackground(new java.awt.Color(204, 204, 204));
        Limipiar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Limipiar.setText("Limpiar");
        Limipiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimipiarActionPerformed(evt);
            }
        });
        jPanel1.add(Limipiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 160, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtIDTrimestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDTrimestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDTrimestreActionPerformed

    private void txtIDCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDCursoActionPerformed

    private void txtIDEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDEstudianteActionPerformed

    private void txtNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaActionPerformed

    private void MenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMousePressed
        this.setVisible(false);
        Menu v = new Menu();
        v.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_MenuMousePressed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:

        if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el ID");
        }
        if (txtIDCurso.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el ID del curso");
        }
        if (txtIDEstudiante.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue ID del estudiante");
        }
        if (txtNota.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue la Nota");
        }
        if (txtIDTrimestre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el Trimestre");
        } else {

            Nota a = new Nota();

            a.setID_NOTAL(Integer.parseInt(txtID.getText()));
            a.setID_CURSO(Integer.parseInt(txtIDCurso.getText()));
            a.setID_TRIMESTRE(Integer.parseInt(txtIDTrimestre.getText()));
            a.setID_ESTUDIANTE(Integer.parseInt(txtIDEstudiante.getText()));
            a.setNOTA(Integer.parseInt(txtNota.getText()));

            String mensaje = aBO.agregarNota(a);
        }
    }//GEN-LAST:event_AgregarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:

        if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el ID");
        }
        if (txtIDCurso.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el ID del curso");
        }
        if (txtIDEstudiante.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue ID del estudiante");
        }
        if (txtNota.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el telefono");
        }
        if (txtIDTrimestre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el nombre del Estudiante");
        } else {

            Nota a = new Nota();

            a.setID_NOTAL(Integer.parseInt(txtID.getText()));
            a.setID_CURSO(Integer.parseInt(txtIDCurso.getText()));
            a.setID_TRIMESTRE(Integer.parseInt(txtIDTrimestre.getText()));
            a.setID_ESTUDIANTE(Integer.parseInt(txtIDEstudiante.getText()));
            a.setNOTA(Integer.parseInt(txtNota.getText()));

            String mensaje = aBO.ModificarNota(a);
        }
    }//GEN-LAST:event_ModificarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        // TODO add your handling code here:

        if (txtID.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Agregue el ID");
        } else {

            String mensaje = aBO.eliminarNota(Integer.parseInt(txtID.getText()));
            System.out.println(mensaje);
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void LimipiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimipiarActionPerformed
        // TODO add your handling code here:
        txtID.setText("");
        txtIDCurso.setText("");
        txtIDEstudiante.setText("");
        txtNota.setText("");
        txtIDTrimestre.setText("");
    }//GEN-LAST:event_LimipiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel IDCurso;
    private javax.swing.JLabel IDEstudiante;
    private javax.swing.JLabel IDTrimestre;
    private javax.swing.JButton Limipiar;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel Nota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDCurso;
    private javax.swing.JTextField txtIDEstudiante;
    private javax.swing.JTextField txtIDTrimestre;
    private javax.swing.JTextField txtNota;
    // End of variables declaration//GEN-END:variables
}
